
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock2
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: TRACE
  file:
    name: logging.log
  pattern:
    console: "%d{yyy-MM-DD HH:mm} == %logger{40} >>> %msg%n"

filters:
  - name: CorsFilter
    class: com.stock.stock.Controller.CorsFilter

application:
  APP_ID: 2358645404637526
  YOUR_URL: https://template.tr1.com.br/redirect
  CLIENT_SECRET: zfLVWLtLJkJuefdI1TlM3xVSG5LYFg8E
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8082