
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: postgres
    password: 415263
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


filters:
  - name: CorsFilter
    class: com.stock.stock.Controller.CorsFilter

application:
  APP_ID: 2358645404637526
  YOUR_URL: https://template.tr1.com.br/redirect
  CLIENT_SECRET: zfLVWLtLJkJuefdI1TlM3xVSG5LYFg8E
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8082